import { LookupItem } from '../models/item.model';

export const lookupItem = [
  {
    Name: 'ADVT. MATERIAL BANNER',
    Code: '',
    MRP: '5.0',
    Price: '0.0',
    Category: 'ADVERTISING_MATERIAL',
  },
  {
    Name: 'ADVT. MATERIAL HANGER',
    Code: '',
    MRP: '5.0',
    Price: '0.0',
    Category: 'ADVERTISING_MATERIAL',
  },
  {
    Name: 'ADVT. MATERIAL STAND',
    Code: '',
    MRP: '300.0',
    Price: '300.0',
    Category: 'ADVERTISING_MATERIAL',
  },
  {
    Name: 'Solid Masti',
    Code: '',
    MRP: '10.0',
    Price: '87.0',
    Category: 'N/A',
  },
  {
    Name: 'Puff Conn',
    Code: '',
    MRP: '0.0',
    Price: '105.0',
    Category: 'N/A',
  },
  {
    Name: 'Paperboat',
    Code: '',
    MRP: '10.0',
    Price: '470.0',
    Category: 'N/A',
  },

  {
    Name: 'FARALI MITHA 400GM',
    Code: '',
    MRP: '85.0',
    Price: '82.0',
    Category: '400GM',
  },
  {
    Name: 'FARALI TIKHA 400GM',
    Code: '',
    MRP: '85.0',
    Price: '72.0',
    Category: '400GM',
  },
  {
    Name: 'FULWADI 400GM',
    Code: '',
    MRP: '85.0',
    Price: '72.0',
    Category: '400GM',
  },
  {
    Name: 'KACHORI 400GM',
    Code: '',
    MRP: '95.0',
    Price: '82.0',
    Category: '400GM',
  },
  {
    Name: 'TIKHA MITHA 400GM',
    Code: '',
    MRP: '85.0',
    Price: '72.0',
    Category: '400GM',
  },
  {
    Name: 'GUJARATI CHAWANA 1KG',
    Code: '',
    MRP: '215.0',
    Price: '162.0',
    Category: '1KG',
  },

  {
    Name: 'BANANA CHIPS 130GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'CHILLY HARISSA 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'CHILLY TADKA 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'CREAMY ONION CHIPS 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'ROCK SALTED CHIPS 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'MAGICAL MASALA CHIPS 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'SIMPLY SALTED CHIPS 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'TWISTED TOMATO CHIPS 135GM',
    Code: '',
    MRP: '40.0',
    Price: '34.0',
    Category: '200GM',
  },
  {
    Name: 'ALOO SEV 200GM',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: '200GM',
  },
  {
    Name: 'BHAKHARWADI 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'BHAVNAGRI GANTHIYA 200GM',
    Code: '',
    MRP: '40.0',
    Price: '0.0',
    Category: '200GM',
  },
  {
    Name: 'CHAKLI 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'DAL MUTH 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'KHATTA MITHAA 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'FARALI MITHA 200GM',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: '200GM',
  },
  {
    Name: 'FARALI TIKHA 200GM',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: '200GM',
  },
  {
    Name: 'METHI MATTHI 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'MINI SAMOSA 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'MOONGDAL 200GM',
    Code: '',
    MRP: '45.0',
    Price: '40.0',
    Category: '200GM',
  },
  {
    Name: 'MORI SEV 200GM',
    Code: '',
    MRP: '40.0',
    Price: '0.0',
    Category: '200GM',
  },
  {
    Name: 'MURUKKU 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'PANCHRATNA COOKIES 200GM',
    Code: '',
    MRP: '95.0',
    Price: '76.0',
    Category: '200GM',
  },
  {
    Name: 'PLAIN PAPDI 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'SAKKARPARA 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'SING BHUJIYA 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'SOAN PAPADI 200GM',
    Code: '',
    MRP: '75.0',
    Price: '40.0',
    Category: '200GM',
  },
  {
    Name: 'SOAN PAPADI 400GM',
    Code: '',
    MRP: '75.0',
    Price: '40.0',
    Category: '400GM',
  },
  {
    Name: 'SOYA STICK 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'TIKHA MITHA 200GM',
    Code: '',
    MRP: '45.0',
    Price: '36.0',
    Category: '200GM',
  },
  {
    Name: 'VANELA GANTHIYA 200GM',
    Code: '',
    MRP: '40.0',
    Price: '0.0',
    Category: '200GM',
  },

  {
    Name: 'SING CHIKKI 500GM',
    Code: '',
    MRP: '0.0',
    Price: '96.0',
    Category: 'CHIKKI',
    Sequence: 5,
  },
  {
    Name: 'MAVA CHIKKI 500GM',
    Code: '',
    MRP: '0.0',
    Price: '96.0',
    Category: 'CHIKKI',
    Sequence: 6,
  },
  {
    Name: 'MAVA CHIKKI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '140.0',
    Category: 'CHIKKI',
    Sequence: 2,
  },
  {
    Name: 'SING CHIKKI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '140.0',
    Category: 'CHIKKI',
    Sequence: 1,
  },
  {
    Name: 'TAL CHIKKI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '160.0',
    Category: 'CHIKKI',
    Sequence: 3,
  },

  {
    Name: 'GREEN CHILLI PAPAD (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '8.0',
    Category: 'PAPAD',
    Sequence: 1,
  },
  {
    Name: 'UDAD MARI PAPAD (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '8.0',
    Category: 'PAPAD',
    Sequence: 2,
  },

  {
    Name: 'SWEETROLL CHOCOLATE (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '192.0',
    Category: 'SWEET_ROLL',
    Sequence: 1,
  },
  {
    Name: 'SWEETROLL VANILLA (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '192.0',
    Category: 'SWEET_ROLL',
    Sequence: 2,
  },

  {
    Name: 'BANANA CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 1,
  },
  {
    Name: 'CHILLY HARISSA CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 14,
  },
  {
    Name: 'CHILLY HARISSA CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 8,
  },
  {
    Name: 'CHILLY TADKA CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 13,
  },
  {
    Name: 'CHILLY TADKA CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 7,
  },
  {
    Name: 'CREAMY ONION CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 12,
  },
  {
    Name: 'CREAMY ONION CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 5,
  },
  {
    Name: 'ROCK SALTED CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
  },
  {
    Name: 'ROCK SALTED CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 6,
  },
  {
    Name: 'MAGICAL MASALA CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 10,
  },
  {
    Name: 'MAGICAL MASALA CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 3,
  },
  {
    Name: 'SIMPLY SALTED CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 9,
  },
  {
    Name: 'SIMPLY SALTED CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 2,
  },
  {
    Name: 'TWISTED TOMATO CHIPS (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'WAFERS',
    Sequence: 11,
  },
  {
    Name: 'TWISTED TOMATO CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'WAFERS',
    Sequence: 4,
  },
  {
    Name: 'CHOCO BITES (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'WAFERS',
    Sequence: 12,
  },

  {
    Name: 'WAFER BISCUIT CHOCOLATE (Rs.5)',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'WAFER_BISCUIT',
  },
  {
    Name: 'WAFER BISCUIT ORANGE (Rs.5)',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'WAFER_BISCUIT',
  },
  {
    Name: 'WAFER BISCUIT STRAWBERRY (RS.5)',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'WAFER_BISCUIT',
  },

  {
    Name: 'CHATAKA MASALA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'CHATAKA_DHAMAKA',
    Sequence: 1,
  },
  {
    Name: 'CHATAKA TOMATO (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'CHATAKA_DHAMAKA',
    Sequence: 2,
  },

  {
    Name: 'CHEESE POP CORN (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'POPCORN',
    Sequence: 2,
  },
  {
    Name: 'POP CORN (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '52.0',
    Category: 'POPCORN',
    Sequence: 1,
  },

  {
    Name: 'CHATPATA TRIANGLE (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 9,
  },
  {
    Name: 'CHATPATI KATORI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 1,
  },
  {
    Name: 'CHAUMIN NOODLES (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 6,
  },
  {
    Name: 'CHINESE PASTA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 12,
  },
  {
    Name: 'JEERA PAPAD (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 5,
  },
  {
    Name: 'KHATTI MITHI RING (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 11,
  },
  {
    Name: 'MASALA PANIPURI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 3,
  },
  {
    Name: 'MASALA WHEELS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 8,
  },
  {
    Name: 'PUDINA RING (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 7,
  },
  {
    Name: 'SALTED REFILL (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 2,
  },
  {
    Name: 'TOMATO KATORI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 10,
  },
  {
    Name: 'TOMCHI ABCD (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'FRYUMS',
    Sequence: 4,
  },

  {
    Name: 'ALOO SEV (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 1,
  },
  {
    Name: 'BHAKHARWADI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 11,
  },
  {
    Name: 'BHAVNAGRI GANTHIYA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 2,
  },
  {
    Name: 'BIKANERI SEV (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
  },
  {
    Name: 'CHANA CHATAKA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 22,
  },
  {
    Name: 'CHANADAL (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 12,
  },
  {
    Name: 'DAL MUTH (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 23,
  },
  {
    Name: 'FARALI MITHA (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'NAMKEEN',
    Sequence: 16,
  },
  {
    Name: 'FARALI MITHA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 18,
  },
  {
    Name: 'FARALI TIKHA (Rs.10)',
    Code: '',
    MRP: '10.0',
    Price: '100.0',
    Category: 'NAMKEEN',
    Sequence: 17,
  },
  {
    Name: 'FARALI TIKHA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 19,
  },
  {
    Name: 'FULWADI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 15,
  },
  {
    Name: 'KHATTA MITHA MIX (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 6,
  },
  {
    Name: 'MAKAI CHIWDA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
  },
  {
    Name: 'MASALA SEV MAMRA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 9,
  },
  {
    Name: 'MOONGDAL (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 13,
  },
  {
    Name: 'MORI SEV (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 5,
  },
  {
    Name: 'MUNCH MIX (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 21,
  },
  {
    Name: 'MURUKKU (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 10,
  },
  {
    Name: 'NAYLON GANTHIYA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 3,
  },
  {
    Name: 'RATLAMI SEV (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 14,
  },
  {
    Name: 'SAKKARPARA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 20,
  },
  {
    Name: 'SEV MAMRA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 8,
  },
  {
    Name: 'SEV MAMRA (Rs.10)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 8,
  },
  {
    Name: 'MASALA SEV MAMRA (Rs.10)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 9,
  },
  {
    Name: 'SING BHUJIYA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 4,
  },
  {
    Name: 'SOYA STICK (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 24,
  },
  {
    Name: 'TIKHA MITHA MIX (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
    Sequence: 7,
  },
  {
    Name: 'TIKHI SEV (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN',
  },

  {
    Name: 'MASALA PAPDI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN_12',
    Sequence: 2,
  },
  {
    Name: 'PLAIN PAPDI (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN_12',
    Sequence: 1,
  },
  {
    Name: 'SOYA CHIPS (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN_12',
    Sequence: 4,
  },
  {
    Name: 'VANELA GANTHIYA (Rs.5)',
    Code: '',
    MRP: '5.0',
    Price: '51.0',
    Category: 'NAMKEEN_12',
    Sequence: 3,
  },

  {
    Name: 'BUSTER BABY PAN',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'BUSTER CHOCOLATE PAN',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY BUTTER GOLD',
    Code: '',
    MRP: '250.0',
    Price: '200.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY CAFETTO JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY CARAMEL ECLAIR JAR',
    Code: '',
    MRP: '340.0',
    Price: '280.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY DARLING SECRET (200pc) JAR',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY DARLING SECRET JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY DARLING VELVETTO JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'Dclair Lollipop HANGER',
    Code: '',
    MRP: '240.0',
    Price: '195.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY KAIREEZ (200PC) JAR',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY KAIREEZ JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY MENTHODEX JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY NARANJA JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY PANVAA JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY SOUR LOVER JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY TAMILY JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'Tim Buk Tu Gum Lollipop HANGER',
    Code: '',
    MRP: '240.0',
    Price: '195.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY TIMBUKTU MIX LOLLIPOP',
    Code: '',
    MRP: '240.0',
    Price: '195.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'Tim Buk Tu Lollipop JAR',
    Code: '',
    MRP: '300.0',
    Price: '250.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'Tim Buk Tu Lollipop STAND',
    Code: '',
    MRP: '350.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'Tim Buk Tu Strawberry Lollipop HANGER',
    Code: '',
    MRP: '240.0',
    Price: '190.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY TROPIC JAR',
    Code: '',
    MRP: '220.0',
    Price: '185.0',
    Category: 'DERBY_JAR',
  },
  {
    Name: 'DERBY VITAMIC C JAR',
    Code: '',
    MRP: '300.0',
    Price: '240.0',
    Category: 'DERBY_JAR',
  },

  {
    Name: 'DERBY ECLAIR CARAMEL POUCH',
    Code: '',
    MRP: '100.0',
    Price: '85.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY CAFETTO POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY COCONUT POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY DARLING SECRET POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY DARLING VELVETTO POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'Dry Fruit Eclairs (100 Pc) POUCH',
    Code: '',
    MRP: '200.0',
    Price: '160.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY ECLAIR CRUNCHEEZ POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY ECLAIR COCONUT POUCH',
    Code: '',
    MRP: '100.0',
    Price: '80.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY ECLAIR ELAICHI POUCH',
    Code: '',
    MRP: '100.0',
    Price: '80.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY ECLAIR MILK POUCH',
    Code: '',
    MRP: '100.0',
    Price: '80.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY EMBOSSIE POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY FRU10 BLACK CURRENT',
    Code: '',
    MRP: '120.0',
    Price: '100.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY FRU10 GREEN APPLE',
    Code: '',
    MRP: '120.0',
    Price: '100.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY FRU10 ORANGE',
    Code: '',
    MRP: '120.0',
    Price: '100.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY FRU10 STRAWBERRY',
    Code: '',
    MRP: '120.0',
    Price: '100.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY HAPPY BIRTHDAY POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY KAIREEZ POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY KUNAFA POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY NARANJA STRIP',
    Code: '',
    MRP: '120.0',
    Price: '100.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY NARANJA POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY PANVAA POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY SOUR LOVER (166PC) POUCH',
    Code: '',
    MRP: '166.0',
    Price: '130.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY SOUR LOVER POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY TAMILY (166PC) POUCH',
    Code: '',
    MRP: '166.0',
    Price: '130.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY TAMILY POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY TROPIC POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY VITAMIC C (100PC) POUCH',
    Code: '',
    MRP: '100.0',
    Price: '80.0',
    Category: 'DERBY_POUCH',
  },
  {
    Name: 'DERBY VITAMIC C POUCH',
    Code: '',
    MRP: '50.0',
    Price: '40.0',
    Category: 'DERBY_POUCH',
  },

  {
    Name: 'MUNCHI CHOCO ROLL',
    Code: '',
    MRP: '160.0',
    Price: '100.0',
    Category: 'MUNCHI_ROLL',
  },
  {
    Name: 'MUNCHI COCONUT ROLL',
    Code: '',
    MRP: '160.0',
    Price: '100.0',
    Category: 'MUNCHI_ROLL',
  },
  {
    Name: 'MUNCHI STRAWBERRY ROLL',
    Code: '',
    MRP: '160.0',
    Price: '100.0',
    Category: 'MUNCHI_ROLL',
  },
];

export const categoryList = [
  {
    Id: 1,
    Name: 'POPCORN',
    Sequence: 1,
  },
  {
    Id: 2,
    Name: 'FRYUMS',
    Sequence: 2,
  },
  {
    Id: 3,
    Name: 'NAMKEEN',
    Sequence: 3,
  },
  {
    Id: 4,
    Name: 'NAMKEEN_12',
    Sequence: 4,
  },
  {
    Id: 5,
    Name: 'CHATAKA_DHAMAKA',
    Sequence: 5,
  },
  {
    Id: 6,
    Name: 'WAFERS',
    Sequence: 6,
  },
  {
    Id: 7,
    Name: 'WAFER_BISCUIT',
    Sequence: 7,
  },
  {
    Id: 8,
    Name: '400GM',
    Sequence: 8,
  },
  {
    Id: 9,
    Name: '200GM',
    Sequence: 9,
  },
  {
    Id: 10,
    Name: 'CHIKKI',
    Sequence: 10,
  },
  {
    Id: 11,
    Name: 'PAPAD',
    Sequence: 11,
  },
  {
    Id: 12,
    Name: 'SWEET_ROLL',
    Sequence: 12,
  },
  {
    Id: 13,
    Name: 'MUNCHI_ROLL',
    Sequence: 13,
  },
  {
    Id: 14,
    Name: 'DERBY_JAR',
    Sequence: 14,
  },
  {
    Id: 15,
    Name: 'DERBY_POUCH',
    Sequence: 15,
  },
  {
    Id: 16,
    Name: '1KG',
    Sequence: 16,
  },
  {
    Id: 17,
    Name: 'ADVERTISING_MATERIAL',
    Sequence: 17,
  },
  {
    Id: 18,
    Name: 'REAL_BITES',
    Sequence: 18,
  },
];
